# kafka输入源
[[sources]]
enable = true
key = "k1"
connect = "kafka_src"
tags = ["src:kafka","topic:wp.input.event"]
params= { topic = "wp.input.event" ,brokers = "localhost:9092" ,group_id="k1"}

# TCP输入源
[[sources]]
enable =  true
key = "tcp_1"
connect = "tcp_src"
params = { prefer_newline = true , port =19002, instances = 1}
tags = ["src:tcp"]

# # TCP输入源
# [[sources]]
# enable =  true
# key = "tcp_2"
# connect = "tcp_src"
# params = { prefer_newline = true , port =19002, instances = 1}
# tags = ["src:tcp-2"]