version = "1.0"

[generator]
mode = "sample"
count = 10000000000000000
speed = 100
parallel = 10

[output]
# 仅当存在 connect 时，其他 output 字段和旧式 [output.*] 子块将被忽略
name = "gen_out"
connect = "tcp_sink"
params = { port= 5170 }

[logging]
level = ""
module_levels = []
output = ""
file_path = "./data/logs"