version = "1.0"

[generator]
mode = "sample"
count = 10000000000000000
speed = 1000
parallel = 16

[output]
# 仅当存在 connect 时，其他 output 字段和旧式 [output.*] 子块将被忽略
connect = "kafka_sink"
name = "generator_output"
# 覆写允许的参数（参考 connectors/sink.d 中对应连接器 allow_override）
params= { topic = "wp.k1" ,brokers = "localhost:9092" }

[logging]
level = ""
module_levels = []
output = ""
file_path = "./data/logs"