# TCP输入源
[[sources]]
enable =  true
key = "tcp-1"
connect = "tcp_src"
params = { prefer_newline = true , port =19001, instances = 1}
tags = ["src:tcp"]

# TCP输入源
[[sources]]
enable =  true
key = "tcp-2"
connect = "tcp_src"
params = { prefer_newline = true , port =19002, instances = 1}
tags = ["src:tcp"]

# [[sources]]
# enable = true
# key = "kafka_input"
# connect = "kafka_src"
# tags = ["src:kafka","topic:wp.input.event"]
# params= { topic = "wp.input.event" ,brokers = "localhost:9092" }