[[sources]]
enable = true
key = "k1"
connect = "kafka_src"
tags = ["src:k1","topic:wp.k1"]
params= { topic = "wp.k1" ,brokers = "localhost:9092" ,group_id="k1"}

# TCP输入源
[[sources]]
enable =  true
key = "kafka-t1"
connect = "tcp_src"
params = { prefer_newline = true , port =19003, instances = 1}
tags = ["src:tcp"]