version = "2.0"

[sink_group]
name = "miss"
oml = []

[[sink_group.sinks]]
name = "miss_output"
connect = "file_raw_sink"
params = {  file = "miss.dat" }
tags = ["sink:miss", "format:raw"]

[sink_group.sinks.expect]
max = 2.0
