version = "2.0"

[sink_group]
name = "monitor"

[[sink_group.sinks]]
name = "monitor_output"
connect = "file_proto_sink"
params = {  file = "monitor.dat" }


[[sink_group.sinks]]
name = "victoriametrics"
connect = "victoriametrics_sink"