[[connectors]]
id = "tcp_src"
type = "tcp"
# 允许覆写的键，兼容 syslog 的常见命名
allow_override = ["addr", "port", "framing", "tcp_recv_bytes", "prefer_newline","instances"]

[connectors.params]
addr = "0.0.0.0"
port = 9000
framing = "auto"          # auto|line|len
prefer_newline = false     # 当 framing=auto 时，是否优先按行
#tcp_recv_bytes = 10485760  # 10 MiB
tcp_recv_bytes = 262144# 1 MiB
